@baseUrl = http://localhost:3000/api
@authToken = {{login.response.body.user.token}}

### Register user 
# @name register

POST  {{baseUrl}}/users/register
Content-Type: application/json

{
    "username": "teszt1",
    "email": "teszt@gmail.com",
    "password": "Teszt123",
    "gender": "férfi",
    "defAddress": "1000, Teszt, teszt1",
    "favCategories": "",
    "birthDate":"2000-01-01",
    "image":"",
    "role": "user",
    "status": "active"
}

### login user
# @name login

POST  {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "Teszt@gmail.com",
    "password": "Teszt123"
}

### login company
# @name CompanyLogin

POST  {{baseUrl}}/company/login
Content-Type: application/json

{
    "email": "asd@gmail.com",
    "password": "asd123"
}

### update password
# @name password

PATCH {{baseUrl}}/users/password/15abfcd3-ead0-4acc-bee4-e31ef9b89db9
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "password": "Teszt321",
    "confirm": "Teszt321"
}

### update email
# @name email

PATCH {{baseUrl}}/users/email/0242be39-ba20-4539-a776-8b8b2b3916e4
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "email": "teszt@gmail.com"
}

### update username
# @name username

PATCH {{baseUrl}}/users/username/58c45e17-3c68-4d52-9e1b-be2113737156
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "username": "asd123"
}


### EVENTS ###

### New Event
# @name newEvent
POST {{baseUrl}}/event/newevent
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "eventName": "5km futás",
    "eventStart": "09:00",
    "eventEnd": "13:00",
    "eventAddress": "6500, Baja, Petőfi Sziget",
    "eventDate": "2025-04-05",
    "userId": "282e7baa-49af-40f6-aa7a-fe160f54631f",
    "catId": "3 10 2",
    "description": "nagyon jo esemény gyere el"

}

### Get all Events
# @name getAll
GET {{baseUrl}}/event/get
Authorization: Bearer {{authToken}}

### Get one Event by id
# @name getOneById
GET {{baseUrl}}/event/get/ae832f03-c39b-4da7-a162-bbde95563621
Authorization: Bearer {{authToken}}

### Delete Event
# @name deleteEvent
DELETE {{baseUrl}}/event/delete/89c01c2a-9448-4fde-8339-93f183b69f5e 
Content-Type: application/json 
Authorization: Bearer {{authToken}}

### Update Event
# @name updateEvent

PATCH  {{baseUrl}}/event/update/5d4ead95-2241-45e9-9080-f033cbc3f66f
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "eventName": "Módosítás"
}


### EVENT RATINGS ###

### New Rating
# @name newRating
POST {{baseUrl}}/eventrating/new
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "rating":"5",
    "opinion":"szuper volt",
    "userId":"282e7baa-49af-40f6-aa7a-fe160f54631f",
    "eventId":"ae832f03-c39b-4da7-a162-bbde95563621"
}

### Update Rating
# @name updateRating
PATCH {{baseUrl}}/eventrating/update/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "rating":"4",
    "opinion":"jó volt"
}

### Delete Rating
# @name DeleteRating
DELETE {{baseUrl}}/eventrating/delete/1
Content-Type: application/json 
Authorization: Bearer {{authToken}}

### Get all Ratings
# @name getAll
GET {{baseUrl}}/eventrating/get
Authorization: Bearer {{authToken}}

### Get one Rating by id
# @name getOneById
GET {{baseUrl}}/eventrating/get/1
Authorization: Bearer {{authToken}}


### Event Registrations ###

### New Registration
# @name newRegistration
POST {{baseUrl}}/eventregistrations/new
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "userId":"282e7baa-49af-40f6-aa7a-fe160f54631f",
    "eventId":"ae832f03-c39b-4da7-a162-bbde95563621"
}

### Get all Registrations
# @name getAll
GET {{baseUrl}}/eventregistrations/get
Authorization: Bearer {{authToken}}

### Get all Registration by id
# @name getAllById
GET {{baseUrl}}/eventregistrations/get/58c45e17-3c68-4d52-9e1b-be2113737156
Authorization: Bearer {{authToken}}

### Delete Registration
# @name DeleteRating
DELETE {{baseUrl}}/eventregistrations/delete/2
Content-Type: application/json 
Authorization: Bearer {{authToken}}


### Categories ###

### Get all Categories
# @name getAll
GET {{baseUrl}}/categories/get
Authorization: Bearer {{authToken}}